[CartPole-v1]

[CartPole-v1.Reinforce]
gamma = 0.99
policy_lr = 0.0001
batch_size = 32
info_step = 1000


[CartPole-v1.ActorCritic]
gamma = 0.7
actor_lr = 0.0001
critic_lr = 0.0001
batch_size = 32
info_step = 1000

[CartPole-v1.DQN]
gamma = 0.99
lr = 0.0001
batch_size = 32
info_step = 1000
buffer_size = 1000000
epsilon_decay_step = 2000
epsilon_decay_factor = 0.99
training_start = 3000
target_update_step = 10

[CartPole-v1.VanillaActorCritic]
gamma = 0.99
value_lr = 0.0001
policy_lr = 0.0001
buffer_size = 10000
batch_size = 32
info_step = 1000

[Pendulum-v1]

[Pendulum-v1.DeepDeterministicPolicyGradient]
gamma = 0.99
policy_lr = 0.0001
critic_lr = 0.0001
batch_size = 32
buffer_size = 100000
info_step = 1000
polyak = 0.8
start_noise_std = 1
noise_std_decay_factor = 0.99
noise_std_decay_freq = 1000
training_start = 2000

